/**
 * This class is generated by jOOQ
 */
package net.lipecki.vote.db;


import javax.annotation.Generated;

import net.lipecki.vote.db.tables.Databasechangeloglock;
import net.lipecki.vote.db.tables.Votes;
import net.lipecki.vote.db.tables.records.DatabasechangeloglockRecord;
import net.lipecki.vote.db.tables.records.VotesRecord;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<VotesRecord, Integer> IDENTITY_VOTES = Identities0.IDENTITY_VOTES;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DatabasechangeloglockRecord> PK_DATABASECHANGELOGLOCK = UniqueKeys0.PK_DATABASECHANGELOGLOCK;
    public static final UniqueKey<VotesRecord> PK_VOTES = UniqueKeys0.PK_VOTES;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<VotesRecord, Integer> IDENTITY_VOTES = createIdentity(Votes.VOTES, Votes.VOTES.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<DatabasechangeloglockRecord> PK_DATABASECHANGELOGLOCK = createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, "PK_DATABASECHANGELOGLOCK", Databasechangeloglock.DATABASECHANGELOGLOCK.ID);
        public static final UniqueKey<VotesRecord> PK_VOTES = createUniqueKey(Votes.VOTES, "PK_VOTES", Votes.VOTES.ID);
    }
}
