/**
 * This class is generated by jOOQ
 */
package net.lipecki.vote.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_F05C0075_5566_4FF6_9FE9_E4176155B857</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_F05C0075_5566_4FF6_9FE9_E4176155B857 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_F05C0075_5566_4FF6_9FE9_E4176155B857", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
