/**
 * This class is generated by jOOQ
 */
package net.lipecki.vote.db;


import javax.annotation.Generated;

import net.lipecki.vote.db.tables.Databasechangelog;
import net.lipecki.vote.db.tables.Databasechangeloglock;
import net.lipecki.vote.db.tables.Votes;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.DATABASECHANGELOGLOCK</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>PUBLIC.DATABASECHANGELOG</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>PUBLIC.VOTES</code>.
     */
    public static final Votes VOTES = Votes.VOTES;
}
